version: "3.3"

services:
    flask_app:
        container_name: flask_app
        restart: always
        build: ./flask_app
        env_file:
            - ./flask_app/.env
        volumes:
            - ~/wehelp/stage3/flask_app/.aws/.:/usr/src/flask_app/.aws
        ports:
            - "8000:8000"
        command: gunicorn -w 2 -b 0.0.0.0:8000 wsgi:app

    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - flask_app
